using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using SplashSphere.Domain.Entities;

namespace SplashSphere.Infrastructure.Persistence.Configurations;

public sealed class TransactionConfiguration : IEntityTypeConfiguration<Transaction>
{
    public void Configure(EntityTypeBuilder<Transaction> builder)
    {
        builder.ToTable("Transactions");

        // ── Primary key ───────────────────────────────────────────────────────
        // ULID generated by the Application layer — never DB-generated
        builder.HasKey(t => t.Id);
        builder.Property(t => t.Id)
            .IsRequired()
            .HasMaxLength(26)       // ULID = 26 base-32 characters
            .ValueGeneratedNever();

        // ── Scalar properties ─────────────────────────────────────────────────
        builder.Property(t => t.TenantId)
            .IsRequired()
            .HasMaxLength(256);

        builder.Property(t => t.BranchId)
            .IsRequired()
            .HasMaxLength(36);

        // References User.Id (internal UUID), not User.ClerkUserId
        builder.Property(t => t.CashierId)
            .IsRequired()
            .HasMaxLength(36);

        builder.Property(t => t.CarId)
            .IsRequired()
            .HasMaxLength(36);

        builder.Property(t => t.CustomerId)
            .HasMaxLength(36);

        builder.Property(t => t.PosStationId)
            .HasMaxLength(36);

        // "{BranchCode}-{YYYYMMDD}-{DailySequence}" — e.g. "MKT-20240115-0042"
        builder.Property(t => t.TransactionNumber)
            .IsRequired()
            .HasMaxLength(50);

        builder.Property(t => t.Status)
            .IsRequired()
            .HasConversion<int>();

        builder.Property(t => t.TotalAmount)
            .IsRequired()
            .HasPrecision(10, 2);

        builder.Property(t => t.DiscountAmount)
            .IsRequired()
            .HasPrecision(10, 2);

        builder.Property(t => t.TaxAmount)
            .IsRequired()
            .HasPrecision(10, 2);

        builder.Property(t => t.FinalAmount)
            .IsRequired()
            .HasPrecision(10, 2);

        builder.Property(t => t.TipAmount)
            .IsRequired()
            .HasPrecision(10, 2)
            .HasDefaultValue(0m);

        builder.Property(t => t.Notes);

        // Null until status transitions to Completed / Cancelled / Refunded
        builder.Property(t => t.CompletedAt);
        builder.Property(t => t.CancelledAt);
        builder.Property(t => t.RefundedAt);
        builder.Property(t => t.RefundReason).HasMaxLength(500);

        // ── Audit timestamps ──────────────────────────────────────────────────
        builder.Property(t => t.CreatedAt)
            .IsRequired()
            .HasDefaultValueSql("now()");

        builder.Property(t => t.UpdatedAt)
            .IsRequired();

        // ── Relationships ─────────────────────────────────────────────────────
        builder.HasOne(t => t.Tenant)
            .WithMany()
            .HasForeignKey(t => t.TenantId)
            .OnDelete(DeleteBehavior.Cascade);

        // Restrict: cannot delete a branch that has transaction history
        builder.HasOne(t => t.Branch)
            .WithMany(b => b.Transactions)
            .HasForeignKey(t => t.BranchId)
            .OnDelete(DeleteBehavior.Restrict);

        // Named Cashier relationship — User entity has no inverse nav for transactions
        builder.HasOne(t => t.Cashier)
            .WithMany()
            .HasForeignKey(t => t.CashierId)
            .OnDelete(DeleteBehavior.Restrict);

        // Restrict: cannot delete a car that has transaction history
        builder.HasOne(t => t.Car)
            .WithMany(c => c.Transactions)
            .HasForeignKey(t => t.CarId)
            .OnDelete(DeleteBehavior.Restrict);

        // SetNull: customer records can be deleted; transactions remain for audit
        builder.HasOne(t => t.Customer)
            .WithMany(c => c.Transactions)
            .HasForeignKey(t => t.CustomerId)
            .IsRequired(false)
            .OnDelete(DeleteBehavior.SetNull);

        // SetNull on station deletion — removing a station should not erase
        // transaction history; the station ID just becomes null and the
        // transaction stops broadcasting future updates (the customer-facing
        // display would already have been switched off in that scenario).
        builder.HasOne(t => t.PosStation)
            .WithMany()
            .HasForeignKey(t => t.PosStationId)
            .IsRequired(false)
            .OnDelete(DeleteBehavior.SetNull);

        // One-to-one with QueueEntry — FK is on QueueEntry.TransactionId (dependent side)
        // Configured from the QueueEntry side in QueueEntryConfiguration
        // EF Core discovers the inverse navigation (Transaction.QueueEntry) automatically

        // ── Unique constraint ─────────────────────────────────────────────────
        // TransactionNumber encodes branch code + date, so unique per tenant is sufficient
        builder.HasIndex(t => new { t.TenantId, t.TransactionNumber })
            .IsUnique();

        // ── Additional indexes ────────────────────────────────────────────────
        builder.HasIndex(t => t.TenantId);
        builder.HasIndex(t => t.BranchId);

        // Dashboard: pending/in-progress transactions per branch
        builder.HasIndex(t => new { t.BranchId, t.Status });

        // Daily summary: all transactions for a branch on a given day
        builder.HasIndex(t => new { t.BranchId, t.CreatedAt });

        // Reconnect-sync lookup: find the active transaction for a station.
        // Filtered to Pending/InProgress so terminal-state rows don't bloat
        // the index. (TransactionStatus 0=Pending, 1=InProgress)
        builder.HasIndex(t => new { t.PosStationId, t.Status })
            .HasFilter("\"PosStationId\" IS NOT NULL");
    }
}
