namespace SplashSphere.Domain.Entities;

/// <summary>
/// Represents a vehicle's place in the service queue for a branch.
/// A queue entry can exist <b>before</b> a transaction is created — the entry tracks
/// the vehicle from arrival through to service completion.
/// <para>
/// <b>State machine:</b>
/// <code>
/// Waiting → Called → InService → Completed
///    ↓         ↓
/// Cancelled  NoShow → (back to Waiting via requeue, or terminal)
/// </code>
/// </para>
/// <para>
/// <b>Queue number:</b> <c>Q-{DailySequence}</c> (e.g. "Q-042"), unique per branch per day.
/// Generated by the Application layer before construction.
/// </para>
/// <para>
/// <b>Transaction link:</b> <see cref="TransactionId"/> is the FK for the optional
/// one-to-one relationship with <see cref="Transaction"/>. Set when the cashier calls
/// <c>PATCH /queue/{id}/start</c>, which simultaneously creates the transaction and
/// sets this entry to <see cref="QueueStatus.InService"/>.
/// </para>
/// <para>
/// <b>Priority ordering:</b> <c>Vip (3) &gt; Express (2) &gt; Regular (1)</c>, then FIFO
/// by <see cref="IAuditableEntity.CreatedAt"/> within the same priority tier.
/// </para>
/// </summary>
public sealed class QueueEntry : IAuditableEntity
{
    private QueueEntry() { } // EF Core

    public QueueEntry(
        string tenantId,
        string branchId,
        string queueNumber,
        string plateNumber,
        QueuePriority priority = QueuePriority.Regular,
        string? customerId = null,
        string? carId = null,
        int? estimatedWaitMinutes = null,
        string? preferredServices = null,
        string? notes = null)
    {
        Id = Guid.NewGuid().ToString();
        TenantId = tenantId;
        BranchId = branchId;
        QueueNumber = queueNumber;
        PlateNumber = plateNumber.ToUpperInvariant().Trim();
        Priority = priority;
        Status = QueueStatus.Waiting;
        CustomerId = customerId;
        CarId = carId;
        EstimatedWaitMinutes = estimatedWaitMinutes;
        PreferredServices = preferredServices;
        Notes = notes;
    }

    public string Id { get; set; } = string.Empty;
    public string TenantId { get; set; } = string.Empty;
    public string BranchId { get; set; } = string.Empty;

    /// <summary>Optional — customer may not be registered at time of queuing.</summary>
    public string? CustomerId { get; set; }

    /// <summary>
    /// Optional — the car may not yet exist in the system when the vehicle arrives.
    /// <see cref="PlateNumber"/> is always stored for display purposes regardless.
    /// </summary>
    public string? CarId { get; set; }

    /// <summary>
    /// FK for the optional one-to-one link to <see cref="Transaction"/>.
    /// Null until the cashier starts service (<c>PATCH /queue/{id}/start</c>).
    /// Unique — enforced by a unique index in EF configuration.
    /// </summary>
    public string? TransactionId { get; set; }

    /// <summary>
    /// Daily sequence identifier: <c>Q-{DailySequence}</c> (e.g. "Q-042").
    /// Unique per branch per day. Reset to Q-001 each calendar day.
    /// Composite unique: [BranchId, QueueNumber, TenantId].
    /// </summary>
    public string QueueNumber { get; set; } = string.Empty;

    /// <summary>
    /// Vehicle plate number stored uppercase and trimmed, copied from <see cref="Car"/>
    /// if the car is registered, or entered manually for unregistered vehicles.
    /// Displayed on the queue board (masked for the public display).
    /// </summary>
    public string PlateNumber { get; set; } = string.Empty;

    public QueueStatus Status { get; set; }
    public QueuePriority Priority { get; set; }

    /// <summary>
    /// Estimated minutes until service starts, calculated at queue entry time as:
    /// <c>entriesAhead × averageServiceDurationMinutes</c>.
    /// Updated when entries ahead are removed. Null if it cannot be estimated.
    /// </summary>
    public int? EstimatedWaitMinutes { get; set; }

    /// <summary>
    /// JSON array of service IDs the customer prefers (e.g. <c>["id1","id2"]</c>).
    /// Pre-populates the service selection on the New Transaction screen when the
    /// cashier opens the transaction from this queue entry.
    /// Null means no preference specified.
    /// </summary>
    public string? PreferredServices { get; set; }

    public string? Notes { get; set; }

    // ── Lifecycle timestamps (all UTC) ────────────────────────────────────────

    /// <summary>Set when status transitions to <see cref="QueueStatus.Called"/>. Starts the 5-minute no-show timer.</summary>
    public DateTime? CalledAt { get; set; }

    /// <summary>Set when status transitions to <see cref="QueueStatus.InService"/>. The linked transaction is created at this point.</summary>
    public DateTime? StartedAt { get; set; }

    /// <summary>Set when the linked transaction reaches <see cref="TransactionStatus.Completed"/>.</summary>
    public DateTime? CompletedAt { get; set; }

    /// <summary>Set when status transitions to <see cref="QueueStatus.Cancelled"/>.</summary>
    public DateTime? CancelledAt { get; set; }

    /// <summary>Set by the Hangfire no-show job when the customer does not arrive within 5 minutes of being called.</summary>
    public DateTime? NoShowAt { get; set; }

    public DateTime CreatedAt { get; set; }
    public DateTime UpdatedAt { get; set; }

    // ── Navigations ──────────────────────────────────────────────────────────

    public Tenant Tenant { get; set; } = null!;
    public Branch Branch { get; set; } = null!;
    public Customer? Customer { get; set; }
    public Car? Car { get; set; }

    /// <summary>
    /// The transaction created when service started. Null until
    /// <see cref="QueueStatus.InService"/>. One-to-one optional;
    /// FK (<see cref="TransactionId"/>) lives on this side.
    /// </summary>
    public Transaction? Transaction { get; set; }
}
