using SplashSphere.Domain.Enums;

namespace SplashSphere.Domain.Entities;

/// <summary>
/// Root aggregate for a car wash business owner.
/// The <see cref="Id"/> equals the Clerk Organization ID — set by the application
/// during onboarding, never auto-generated by the database.
/// One tenant may own multiple <see cref="Branch"/> records.
/// </summary>
public sealed class Tenant : IAuditableEntity
{
    private Tenant() { } // EF Core

    public Tenant(string clerkOrgId, string name, string email, string contactNumber, string address)
    {
        Id = clerkOrgId;
        Name = name;
        Email = email;
        ContactNumber = contactNumber;
        Address = address;
    }

    /// <summary>Clerk Organization ID — used as the tenant discriminator on all child rows.</summary>
    public string Id { get; set; } = string.Empty;

    public string Name { get; set; } = string.Empty;
    public string Email { get; set; } = string.Empty;
    public string ContactNumber { get; set; } = string.Empty;
    public string Address { get; set; } = string.Empty;
    public bool IsActive { get; set; } = true;

    // ── Branding (slice 1) ───────────────────────────────────────────────────
    /// <summary>Optional one-liner shown beneath the business name on receipts and the Connect listing.</summary>
    public string? Tagline { get; set; }

    /// <summary>Optional public website URL.</summary>
    public string? Website { get; set; }

    // ── Structured headquarters address ──────────────────────────────────────
    // Each branch carries its own address (Branch.Address). These tenant-level
    // fields are the headquarters / display address used on email receipts,
    // reports, and invoices. Kept nullable so existing tenants don't need a
    // backfill — Address (the legacy single string) is still derived/maintained.
    public string? StreetAddress { get; set; }
    public string? Barangay { get; set; }
    public string? City { get; set; }
    public string? Province { get; set; }
    public string? ZipCode { get; set; }

    // ── Tax & registration ──────────────────────────────────────────────────
    /// <summary>True for VAT-registered businesses (12% PH VAT applies). Most car washes are non-VAT.</summary>
    public bool IsVatRegistered { get; set; }

    // ── Social & payment display ────────────────────────────────────────────
    /// <summary>Full Facebook page URL (e.g. https://facebook.com/aquashinecarwash).</summary>
    public string? FacebookUrl { get; set; }

    /// <summary>Instagram handle, optionally with leading @ (stored as-entered).</summary>
    public string? InstagramHandle { get; set; }

    /// <summary>GCash MSISDN displayed on receipts. Format is free-form (not validated).</summary>
    public string? GCashNumber { get; set; }

    // ── Franchise ────────────────────────────────────────────────────────────
    public TenantType TenantType { get; set; } = TenantType.Independent;
    public string? ParentTenantId { get; set; }
    public string? FranchiseCode { get; set; }
    public string? TaxId { get; set; }
    public string? BusinessPermitNo { get; set; }

    public DateTime CreatedAt { get; set; }
    public DateTime UpdatedAt { get; set; }

    // ── Navigations ──────────────────────────────────────────────────────────

    public ICollection<Branch> Branches { get; set; } = [];
    public ICollection<User> Users { get; set; } = [];
    public ICollection<VehicleType> VehicleTypes { get; set; } = [];
    public ICollection<Size> Sizes { get; set; } = [];
    public ICollection<Make> Makes { get; set; } = [];
    public ICollection<ServiceCategory> ServiceCategories { get; set; } = [];
    public ICollection<MerchandiseCategory> MerchandiseCategories { get; set; } = [];
    public ICollection<QueueEntry> QueueEntries { get; set; } = [];
    public TenantSubscription? Subscription { get; set; }

    // ── Franchise navigations ────────────────────────────────────────────────
    public Tenant? ParentTenant { get; set; }
    public ICollection<Tenant> ChildTenants { get; set; } = [];
    public FranchiseSettings? FranchiseSettings { get; set; }

    // ── Inventory navigations ────────────────────────────────────────────────
    public ICollection<SupplyCategory> SupplyCategories { get; set; } = [];
    public ICollection<SupplyItem> SupplyItems { get; set; } = [];
    public ICollection<Supplier> Suppliers { get; set; } = [];
    public ICollection<Equipment> Equipment { get; set; } = [];
    public ICollection<PurchaseOrder> PurchaseOrders { get; set; } = [];
}
