namespace SplashSphere.Domain.Entities;

/// <summary>
/// Root aggregate for a car wash business owner.
/// The <see cref="Id"/> equals the Clerk Organization ID — set by the application
/// during onboarding, never auto-generated by the database.
/// One tenant may own multiple <see cref="Branch"/> records.
/// </summary>
public sealed class Tenant : IAuditableEntity
{
    private Tenant() { } // EF Core

    public Tenant(string clerkOrgId, string name, string email, string contactNumber, string address)
    {
        Id = clerkOrgId;
        Name = name;
        Email = email;
        ContactNumber = contactNumber;
        Address = address;
    }

    /// <summary>Clerk Organization ID — used as the tenant discriminator on all child rows.</summary>
    public string Id { get; set; } = string.Empty;

    public string Name { get; set; } = string.Empty;
    public string Email { get; set; } = string.Empty;
    public string ContactNumber { get; set; } = string.Empty;
    public string Address { get; set; } = string.Empty;
    public bool IsActive { get; set; } = true;

    public DateTime CreatedAt { get; set; }
    public DateTime UpdatedAt { get; set; }

    // ── Navigations ──────────────────────────────────────────────────────────

    public ICollection<Branch> Branches { get; set; } = [];
    public ICollection<User> Users { get; set; } = [];
    public ICollection<VehicleType> VehicleTypes { get; set; } = [];
    public ICollection<Size> Sizes { get; set; } = [];
    public ICollection<Make> Makes { get; set; } = [];
    public ICollection<ServiceCategory> ServiceCategories { get; set; } = [];
    public ICollection<MerchandiseCategory> MerchandiseCategories { get; set; } = [];
    public ICollection<QueueEntry> QueueEntries { get; set; } = [];
}
