namespace SplashSphere.Domain.Entities;

/// <summary>
/// The central POS aggregate. Records a complete car wash visit: which services/packages
/// were performed, which employees did the work, what merchandise was sold, and how payment
/// was collected.
/// <para>
/// <b>ID strategy:</b> <see cref="Id"/> is a <b>ULID</b> string generated by the caller
/// (<c>Ulid.NewUlid().ToString()</c> in the Application layer) before construction.
/// ULIDs are time-sortable, which keeps transaction rows physically ordered by creation time
/// in the PostgreSQL heap without a separate index.
/// </para>
/// <para>
/// <b>State machine:</b>
/// <code>Pending → InProgress → Completed</code>
/// Cancel is allowed from Pending or InProgress.
/// Refund is allowed only from Completed.
/// </code>
/// </para>
/// <para>
/// <b>Financial fields:</b>
/// <c>FinalAmount = TotalAmount − DiscountAmount + TaxAmount</c>.
/// Multi-payment: the sum of all <see cref="Payments"/> must equal <see cref="FinalAmount"/>
/// before the transaction can reach <see cref="TransactionStatus.Completed"/>.
/// </para>
/// <para>
/// <b>Cascade deletes:</b> all child collections (Services, Packages, Merchandise,
/// Employees, Payments) are deleted when this Transaction is deleted.
/// </para>
/// </summary>
public sealed class Transaction : IAuditableEntity, ITenantScoped
{
    private Transaction() { } // EF Core

    public Transaction(
        string id,
        string tenantId,
        string branchId,
        string cashierId,
        string carId,
        string? customerId = null)
    {
        Id = id;
        TenantId = tenantId;
        BranchId = branchId;
        CashierId = cashierId;
        CarId = carId;
        CustomerId = customerId;
        Status = TransactionStatus.Pending;
    }

    /// <summary>ULID string — time-sortable, generated by the Application layer.</summary>
    public string Id { get; set; } = string.Empty;

    public string TenantId { get; set; } = string.Empty;
    public string BranchId { get; set; } = string.Empty;

    /// <summary>The <see cref="User"/> (cashier) who created the transaction.</summary>
    public string CashierId { get; set; } = string.Empty;

    public string CarId { get; set; } = string.Empty;

    /// <summary>Nullable — walk-in vehicles may not have a registered customer.</summary>
    public string? CustomerId { get; set; }

    /// <summary>
    /// Human-readable transaction identifier: <c>{BranchCode}-{YYYYMMDD}-{DailySequence}</c>
    /// (e.g. "MKT-20240115-0042"). Generated by the handler after the daily sequence is
    /// retrieved from the database; not set in the constructor.
    /// </summary>
    public string TransactionNumber { get; set; } = string.Empty;

    public TransactionStatus Status { get; set; }

    /// <summary>Sum of all line-item prices before adjustments. Precision (10, 2).</summary>
    public decimal TotalAmount { get; set; }

    /// <summary>Total discount applied (e.g. loyalty discount, promo code). Precision (10, 2).</summary>
    public decimal DiscountAmount { get; set; }

    /// <summary>VAT or other tax component. Precision (10, 2).</summary>
    public decimal TaxAmount { get; set; }

    /// <summary>
    /// <c>TotalAmount − DiscountAmount + TaxAmount</c>. Must be fully covered by
    /// <see cref="Payments"/> before the transaction can be completed. Precision (10, 2).
    /// </summary>
    public decimal FinalAmount { get; set; }

    /// <summary>
    /// Optional tip amount paid by the customer on top of <see cref="FinalAmount"/>.
    /// Tips are NOT business revenue — they go directly to employees.
    /// When the tip was collected via a non-cash method (GCash, card, etc.)
    /// the cashier must withdraw the equivalent amount from the cash register
    /// and hand it to the employee(s). Precision (10, 2).
    /// </summary>
    public decimal TipAmount { get; set; }

    public string? Notes { get; set; }

    /// <summary>Loyalty points earned from this transaction (set by the loyalty handler).</summary>
    public int PointsEarned { get; set; }

    /// <summary>Loyalty reward redemption applied to this transaction, if any.</summary>
    public string? LoyaltyRedemptionId { get; set; }

    /// <summary>UTC timestamp when status transitioned to <see cref="TransactionStatus.Completed"/>.</summary>
    public DateTime? CompletedAt { get; set; }

    /// <summary>UTC timestamp when status transitioned to <see cref="TransactionStatus.Cancelled"/>.</summary>
    public DateTime? CancelledAt { get; set; }

    /// <summary>UTC timestamp when status transitioned to <see cref="TransactionStatus.Refunded"/>.</summary>
    public DateTime? RefundedAt { get; set; }

    /// <summary>Reason recorded by the cashier at the time of refund.</summary>
    public string? RefundReason { get; set; }

    public DateTime CreatedAt { get; set; }
    public DateTime UpdatedAt { get; set; }

    // ── Navigations ──────────────────────────────────────────────────────────

    public Tenant Tenant { get; set; } = null!;
    public Branch Branch { get; set; } = null!;

    /// <summary>The cashier who processed this transaction.</summary>
    public User Cashier { get; set; } = null!;

    public Car Car { get; set; } = null!;
    public Customer? Customer { get; set; }

    /// <summary>
    /// The queue entry this transaction was started from, if any.
    /// Inverse of the one-to-one; FK is <see cref="QueueEntry.TransactionId"/>.
    /// </summary>
    public QueueEntry? QueueEntry { get; set; }

    /// <summary>Individual service line items. Cascade delete.</summary>
    public ICollection<TransactionService> Services { get; set; } = [];

    /// <summary>Package line items. Cascade delete.</summary>
    public ICollection<TransactionPackage> Packages { get; set; } = [];

    /// <summary>Merchandise line items. Cascade delete.</summary>
    public ICollection<TransactionMerchandise> Merchandise { get; set; } = [];

    /// <summary>Per-employee commission summary records. Cascade delete.</summary>
    public ICollection<TransactionEmployee> Employees { get; set; } = [];

    /// <summary>Payment records. Cascade delete.</summary>
    public ICollection<Payment> Payments { get; set; } = [];
}
