using SplashSphere.Application.Common.Interfaces;
using SplashSphere.Domain.Enums;
using SplashSphere.SharedKernel.Results;

namespace SplashSphere.Application.Features.Queue.Commands.AddToQueue;

/// <summary>
/// Adds a vehicle to the branch queue. Returns the new QueueEntry ID.
/// Queue number (Q-{DailySequence}) is generated by the handler.
/// EstimatedWaitMinutes is calculated as: WAITING entries ahead × average service duration.
/// </summary>
public sealed record AddToQueueCommand(
    string BranchId,
    string PlateNumber,
    QueuePriority Priority = QueuePriority.Regular,
    string? CustomerId = null,
    string? CarId = null,
    IReadOnlyList<string>? PreferredServiceIds = null,
    string? Notes = null) : ICommand<string>;
